### PR TITLE
Update calculations to assume undistorted space

### PR DESCRIPTION
**Pull request by romanroibu**
Addresses #3

### CODE REVIEW

**Comment by romanroibu** [comment]
hey @s-westphal,

I've updated the library to only use undistorted coordinates. Please try it out and let me know if there are any issues that you find. Thanks!

**Comment by s-westphal** [comment]
hi @romanroibu 
looks good! 
Two more questions:
- Would it be possible to add a surface element as an optional initialization parameter for SurfaceTracker, such that `define_surface` does not need to be called? Or a method `set_surface(surface)` that can be called instead of `define_surface`. This would allow us to save the surface, e.g. in a database, and then later get a SurfaceTracker instance and only locate or modify the surface.
- Can we allow to call `define_surface` with an empty list of markers? Markers are then iteratively added with an `add_markers_to surface` function, and a `locate_surface` can only be called if there are any markers added to the surface 
Thank you!

**Comment by romanroibu** [comment]
Answering your questions:

- You can do this now, there is no need for a `set_surface` method. You can serialize the surface definition, store it somewhere, then deserialize the stored definition and use it with an instance of surface tracker.
- Well, the constraint was that the surface is defined by 1+ markers. I'd have to check what I need to change to relax this constraint. As a workaround, with the iterative approach you suggested, you could define the surface on the first iteration, and then add markers. Also, could you please describe why you need this iterative process?

**Comment by s-westphal** [comment]
for (1) that's perfect, thanks!
for (2) it would be great if it's possible, I didn't know of this constraint, if not, I will have to come up with another solution for our problem
We need it for the enrichments, when you create a surface_tracker enrichment, we would like to intitialize it 'empty' then the user can select a recording and a frame to define the surface. 
There will also be a 'reset'-button that deletes the current surface, so set the makers to an empty list

**Comment by papr** [comment]
@s-westphal Could you elaborate on the problem that you are having? Maybe, @romanroibu can provide you with a solution that fits the existing API design.

**Review by s-westphal — APPROVED** [review]

**Comment by romanroibu** [comment]
Pending review of #6 

---

@marc-tonsen, @euryalus Could you please review the changes in #6 when you have time, and let me and @s-westphal know what you think about it? Thank you!

**Pull request merged**
